name: smart_ride_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.2.0

  cupertino_icons: ^1.0.2
  hive: ^2.2.2
  flutter_secure_storage: ^5.0.2
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  provider: ^6.0.3
  google_maps_flutter: ^2.1.8
  flutter_polyline_points: ^1.0.0
  freezed: ^2.0.3+1
  dio: ^4.0.6
  intl: ^0.17.0
  vector_math: ^2.1.2
  custom_info_window: ^1.0.1
  device_preview: ^1.1.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.4
  flutter_svg: ^1.1.0
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.9.3
  wave: ^0.2.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: false
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#4D77E1" # for background color, use it or the:
  image: assets/images/logo_big.png # It must be a png file and should be sized for 4x pixel density.
  # branding: assets/images/icons/branding_icon.png # Like a company name
  # branding_mode: right # Position of the branding image

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vectors/
  #   - images/a_dot_ham.jpeg
